# Change baseurl before deploy
baseurl = "https://yeonhl.github.io"
languageCode = "ko-kr"
title = "연호의 블로그"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "ko"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "https-yeonhl-github-io"

[pagination]
pagerSize = 5